name: Reusable GitHub Workflow Run Cleanup

on:
  workflow_call:
    inputs:
      days_old:
        description: 'The amount of days old to delete'
        type: string
        default: '0'
        required: false
      runs_to_keep:
        description: 'The amount of latest workflows runs to keep'
        type: string
        default: '2'
        required: false

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v4
        with:
          days_old: ${{ inputs.days_old }}
          runs_to_keep: ${{ inputs.runs_to_keep }}